### ISSUE TITLE
TypeError: $(...).DataTable is not a function

### ISSUE THREAD

**Issue by imike57** [perfectsoft-tunisia/meteor-reactive-responsive-datatables#1]
Hi,

after installed your package, I can't use the global function DataTable() as in your example or in the library example... There is something to do for  ? 

Thank's

Mike

**Comment by ziedmahdi** [comment]
@imike57 you need to install [ jquery.dataTables](https://datatables.net/) by your self, either from npm or using a meteor package or even by dropping the jquery datatables files in your project folder
